### PR TITLE
`--reinstall` flag to force the app to be reinstalled after each launch.

### PR DESCRIPTION
**Pull request by sssionggg**
This PR creates a new `--reinstall` flag.  If the `Installer` app is built with this flag, it will reinstall the app every time when the user launches the app in the simulator. This is helpful if you want to make sure that a clean(clear NSUserDefault for example) app is launched in the simulator.

### CODE REVIEW

**Comment by stepanhruda** [comment]
Nice, you think we could call the flag `--fresh-install`?

**Comment by sssionggg** [comment]
@stepanhruda do you mind changing it?  i will be off for vacation for next week and the branch is on my work laptop :(

**Comment by stepanhruda** [comment]
Of course! Will get this ready tomorrow.

**Comment by stepanhruda** [comment]
I can't push to your branch, so I'm going to merge this and push some more commits into this repo.

**Comment by sssionggg** [comment]
@stepanhruda haha.  thanks!

**Pull request merged**
